### ISSUE TITLE
Isolate eval function to separate package

### ISSUE THREAD

**Issue by Yeti-or** [gulp-bem/gulp-eval#8]
@zxqfox @blond @tadatuta 
1. new-package name - `node-eval`
2. package will be in this oraganization

everybody agree?

**Comment by blond** [comment]
> 1. new-package name - node-eval

👍 

> package will be in this oraganization

Maybe `bem-sdk`?

**Comment by tadatuta** [comment]
I'd keep in `gulp-bem` and 👍 for package name.
